### ISSUE TITLE
too much code

### ISSUE THREAD

**Issue by noahtallen** [ramaleone/TravisCI-Sample2#1]
wait wow you have so many files here, you're too ahead in the class

**Comment by lukemeierj** [comment]
noah makes a good point, have you considered easing up a little?

**Comment by ramaleone** [comment]
I have, actually. I have removed some of the files, I hope this is more to your liking. Let me know! @ntomallen @lukemeierj

**Comment by noahtallen** [comment]
Wow beautiful 👌👌
